micronaut:
  application:
    name: slack-tenor-bot

  http:
    services:
      tenor:
        url: https://tenor.googleapis.com/v2

      slack:
        url: https://slack.com/api

  serde:
    serialization:
      inclusion: non_null

bot:
  credentials:
    tenor:
      api-key: ${TENOR_API_KEY}

    slack:
      bot-token: ${SLACK_BOT_TOKEN}
