micronaut:
  application:
    name: slack-tenor-bot

  http:
    services:
      tenor:
        url: https://tenor.googleapis.com/v2

  serde:
    serialization:
      inclusion: non_null

bot:
  credentials:
    tenor:
      api-key: ${TENOR_API_KEY}
