micronaut:
  application:
    name: slack-tenor-bot

  http:
    services:
      slack:
        url: https://slack.com

      tenor:
        url: https://tenor.googleapis.com/v2

  serde:
    serialization:
      inclusion: NON_NULL

credentials:
  slack:
    bot: ${SLACK_BOT_TOKEN}

  tenor:
    api-key: ${TENOR_API_KEY}
